---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#############################
# Start the job on all push #
#############################
on:
 workflow_dispatch:
 
env:
  DAY_OF_WEEK: Monday
 

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
     - uses: actions/checkout@v3
     - name: run bash from script
       run: |
        chmod +x bash.sh 
        ./bash.sh {{env.DAY_OF_WEEK}} {{env.DAY_OF_WEEK}}
     - name: Run ShellCheck
       uses: azohra/shell-linter@latest
       with:
         path: "setup,bash.sh"
      
