name: Test Python Action

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Python test action
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
         python-version: '3.9' 
      - run: python --version
