name: Test Python Action

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - run: python --version
