name: Test Python Action

on:
 workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.6.15, 3.7.12, 3.8.12, 3.9.9, 3.10.1]
 
    steps:
    - uses: actions/checkout@v2
    - name: Install pyenv
      run: |
        curl https://pyenv.run | bash
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $GITHUB_ENV
        echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> $GITHUB_ENV
        echo 'export PATH="$HOME/.pyenv/shims:$PATH"' >> $GITHUB_ENV
        echo 'eval "$(pyenv init --path)"' >> $GITHUB_ENV
        echo 'eval "$(pyenv init -)"' >> $GITHUB_ENV
        echo 'eval "$(pyenv virtualenv-init -)"' >> $GITHUB_ENV
    - name: Install Python ${{ matrix.python-version }}
      run: |
        source $GITHUB_ENV
        pyenv install ${{ matrix.python-version }}
        pyenv global ${{ matrix.python-version }}
        python -m pip install --upgrade pip
