name: Test Python Action

on:
 workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install pyenv
      run: |
        curl https://pyenv.run | bash
        echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> $GITHUB_ENV
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $GITHUB_ENV
        echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $GITHUB_ENV
        echo 'eval "$(pyenv init --path)"' >> $GITHUB_ENV
        echo 'eval "$(pyenv init -)"' >> $GITHUB_ENV
        echo 'eval "$(pyenv virtualenv-init -)"' >> $GITHUB_ENV
        source $GITHUB_ENV
    - name: Install Python ${{ matrix.python-version }}
      run: |
        pyenv install ${{ matrix.python-version }}
        pyenv global ${{ matrix.python-version }}
        
        #python -m pip install --upgrade pip
      
