name: Test Python Action

on:
 workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: [3.6.15, 3.7.12, 3.8.12, 3.9.9, 3.10.1]
    steps:
    - uses: actions/checkout@v4
    - name: Install pyenv
      run: |
        curl https://pyenv.run| bash
        echo "PYENV_ROOT=$HOME/.pyenv" >> $GITHUB_ENV
        echo "PATH=$HOME/.pyenv/bin:$HOME/.pyenv/shims:$PATH" >> $GITHUB_ENV
    - name: Set up pyenv
      run: |
        echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
        echo 'eval "$(pyenv init -)"' >> ~/.bashrc
        echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
        source ~/.bashrc
    - name: Install Python ${{ matrix.python-version }}
      run: |
        source ~/.bashrc
        pyenv install ${{ matrix.python-version }}
        pyenv global ${{ matrix.python-version }}
        python --version
        python Test.py
        
