name: Hi 
on: 
 workflow_call:
   secrets:
     MASCOT_TOKEN:
       required: false
env:
  mascot: http://www.123.com
  super_duper_var: totally_awesome

jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Mona
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Octocat
        env:
          mascot: Octocat
  linux_job:
    runs-on: ubuntu-latest
    env:
      mascot: Tux
      HAVE_MASCOT_TOKEN: ${{ secrets.MASCOT_TOKEN != '' }}
    steps:
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Tux
      - name: "check is MY_SECRET exists"
        if: ${{ env.HAVE_MASCOT_TOKEN == 'true' }}
        run: echo ${{secrets.MASCOT_TOKEN}}
      - name: "check is Seccret is not passed"   
        if: ${{ env.HAVE_MASCOT_TOKEN == 'false' }}
        run: echo ${{env.mascot}}
